export const appName = "MCRP"

//export const server = "http://localhost:8080" //do not user /
//export const server = "http://192.168.43.164:8080" //do not user /
//export const server = "https://hackpccserver.herokuapp.com"
export const server = "http://45.114.143.15"
export const districtWiseData = {
  "Kasaragod": [
      "Adhur",
      "Ambalathara",
      "Badiadukka",
      "Bedakom",
      "Bekal",
      "Chandera",
      "Cheemeni",
      "Chittarikal",
      "Hosdurg",
      "Kasaragod",
      "Kumbla",
      "Manjeswar",
      "Nileswar",
      "Rajapuram",
      "Vellarikundu",
  ],
  "Kannur": [
      "Alakode",
      "Aralam",
      "Chackarackal",
      "Chockli",
      "Edakkad",
      "Irikkur",
      "Iritty",
      "Kannapuram",
      "Kannavam",
      "Kannur City",
      "Karikottakari",
      "Kathirur",
      "Kelakam",
      "Kolavallur",
      "Kudiyanmala",
      "Kuthuparamba",
      "Maloor",
      "Mattannur",
      "Panur",
      "Payyannur",
      "Payyavoor",
      "Pazhangadi ",
      "Peravoor",
      "Peringome",
      "SHO Dharmadam",
      "SHO Kannur Town",
      "Sreekandapuram",
      "Thalassery",
      "Thaliparamba",
      "Ulikkal",
      "Valapattanam",
  ],
  "Wayanad": [
      "Ambalavayal",
      "Kalpetta",
      "Kambalakkad",
      "Kenichira",
      "Mananthavady",
      "Meenangadi",
      "Meppadi",
      "Padinjarethara",
      "Pulpally",
      "Sulthan Bathery",
      "Thalapuzha",
      "Thirunelly",
      "Vellamunda",
      "Vythiri",
  ],
  "Kozhikode": [
      "Atholy",
      "Balussery",
      "Beypore ",
      "Chemmangad",
      "Chevayur",
      "Edacherry",
      "Elathur",
      "Feroke",
      "Kakkur",
      "Kasaba",
      "Kodenchery",
      "Koduvally",
      "Kooranchundu",
      "Koyilandy",
      "Kozhikode Town",
      "Kunnamangalam",
      "Kuttiyadi",
      "Marad",
      "Mavoor",
      "Medical College",
      "Meppayur",
      "Mukkom",
      "Nadakkavu",
      "Nadapuram",
      "Nallalam",
      "Panniankara",
      "Payyoli",
      "Perambra",
      "Peruvannamuzhy",
      "Thamarassery",
      "Thiruvambadi",
      "Thottilpalam",
      "Valayam",
      "Vanitha",
      "Vatakara",
      "Vellayil",
  ],
  "Malappuram": [
      "Areekode",
      "Changaramkulam",
      "Edakkara",
      "Edavanna",
      "Kalikavu",
      "Kalpakanchery",
      "Karuvarakundu",
      "Kolathur",
      "Kondotty",
      "Kottakkal",
      "Kuttipuram",
      "Malappuram",
      "Manjeri",
      "Melattur",
      "Nilambur",
      "Pandikad",
      "Parappanangadi",
      "Perinthalmanna",
      "Perumpadappu",
      "Ponnani",
      "Pothukal",
      "Tanur",
      "Thenhipalam",
      "Tirur",
      "Tirurangadi",
      "Valanchery",
      "Vazhakkad",
      "Vazhikadavu",
      "Vengara",
      "Wandoor",
  ],
  "Palakkad": [
      "Agali",
      "Alathur",
      "Chalissery",
      "Cherpulassery",
      "Chittur",
      "Hemambika Nagar",
      "Kasaba",
      "Kollengode",
      "Kongad",
      "Kottayi",
      "Kozhinjampara",
      "Kuzhalmannam",
      "Malampuzha ",
      "Mangalam Dam",
      "Mankara",
      "Mannarkkad",
      "Nattukal",
      "Nenmara",
      "Ottappalam",
      "Padagiri",
      "Parambikulam",
      "Pattambi",
      "Pudunagaram",
      "Sholayur",
      "Shornur",
      "Sreekrishnapuram",
      "Thrithala",
      "Town North",
      "Town South",
      "Wadakkancherry",
      "Walayar",
  ],
  "Thrissur": [
      "Athirappally",
      "Azheekode Coastal",
      "Chalakkudy",
      "Chavakkad",
      "Chelakkara",
      "Cherpu",
      "Cheruthuruthy",
      "Erumapetty",
      "Guruvayoor",
      "Irinjalakuda",
      "Kattoor",
      "Kodungallur",
      "Koraty",
      "Kunnamkulam",
      "Mala",
      "Malakkapara",
      "Mannuthy",
      "Mathilakom",
      "Nedupuzha",
      "Ollur",
      "Pavaratty",
      "Pazhayannur",
      "Peechi",
      "Peramangalam",
      "Pudukkad",
      "Town East",
      "Town West",
      "Vadakkanchery",
      "Vadakkekad",
      "Vadanappally",
      "Valappad",
      "Vellikulangara",
      "Viyyur",
  ],
  "Ernakulam": [
      "Aluva",
      "Angamali",
      "Ayyampuzha",
      "Binanipuram",
      "Chengamanad",
      "Kalady",
      "Kalloorkadu",
      "Kodanad",
      "Koothattukulam",
      "Kothamangalam",
      "Kottappady",
      "Kunnathunadu",
      "Kuruppampady",
      "Kuttampuzha",
      "Mulanthuruthy",
      "Munambom",
      "Muvattupuzha",
      "Nedumbassery",
      "Njarakkal",
      "North Parur",
      "Oonnukal",
      "Perumbavoor",
      "Piravom",
      "Pothanikadu ",
      "Puthencruz",
      "Puthenvelikkara",
      "Ramamangalam",
      "Thadiyittaparamba",
      "Vadakkekara",
      "Varapuzha ",
      "Vazhakulam",
      "Ambalamedu",
      "Cheranalloor",
      "Eloor",
      "Ernakulam Central",
      "Ernakulam North (Kasba)",
      "Ernakulam South",
      "Fort Kochi",
      "Harbour",
      "Hill palace",
      "Kadavanthara",
      "Kalamassery",
      "Kannamali",
      "Mattancherry",
      "Mulavukad",
      "Palarivattom",
      "Palluruthy",
      "Panangad",
      "Thoppumpady",
      "Thrikkakara",
      "Traffic East",
      "Traffic West",
      "Udayamperoor",
      "Vanitha PS",
  ],
  "Idukki": [
      "Adimaly",
      "Cumbummettu",
      "Devikulam",
      "Idukki",
      "Kaliyar",
      "Kanjar",
      "Kanjikuzhy",
      "Karimanal",
      "Karimannoor",
      "Karinkunnam",
      "Kattappana",
      "Kulamavu",
      "Kumily",
      "Marayur",
      "Munnar",
      "Murikkassery",
      "Nedumkandam",
      "Peermedu",
      "Peruvanthanam",
      "Rajakkad",
      "Santhanpara",
      "Thodupuzha",
      "Upputhara ",
      "Vandanmedu",
      "Vandiperiyar",
      "Vellathooval",
  ],
  "Kottayam": [
      "Ayarkunnam",
      "Changanassery",
      "Chingavanam",
      "Erattupettah",
      "Erumeli",
      "Ettumanoor",
      "Gandhinagar",
      "Kaduthuruthy",
      "Kanjirappally",
      "Karukachal",
      "Kidangoor",
      "Kottayam East",
      "Kottayam West",
      "Kumarakom",
      "Kuravilangadu",
      "Manarcaud",
      "Manimala",
      "Marangattupally",
      "Melukkavu",
      "Mundakkayam",
      "Pala",
      "Pallikkathode",
      "Pampady",
      "Ponkunnam",
      "Ramapuram",
      "Thidanadu ",
      "Thrikkodithanam",
      "Vaikkom",
      "Vakathanam",
      "Velloor",
  ],
  "Alappuzha": [
      "Alappuzha South",
      "Ambalappuzha",
      "Aroor",
      "Arthungal",
      "Chengannoor",
      "Cherthala",
      "Edathua",
      "Harippad",
      "Kainady",
      "Kanakakunnu",
      "Kareelakulangara",
      "Kayamkulam",
      "Kurathikadu",
      "Kuthiathode",
      "Mannar",
      "Mararikulam",
      "Mavelikkara",
      "Muhamma",
      "Nedumudy",
      "Nooranadu",
      "North",
      "Pattanakkad",
      "Poochakkal",
      "Pulinkunnu",
      "Punnapra",
      "Ramankary",
      "Thrikkunnappuzha",
      "Vallikunnam",
      "Veeyapuram",
      "Venmani",
  ],
  "Pathanamthitta": [
      "Adoor",
      "Aranmula",
      "Chittar",
      "Enath",
      "Keezhvaipur",
      "Kodumon",
      "Koipuram",
      "Konni",
      "Koodal",
      "Moozhiyar",
      "Pampa",
      "Pandalam",
      "Pathanamthitta",
      "Perumpetty",
      "Perunad",
      "Pulikeezhu",
      "Ranni",
      "Thannithodu",
      "Thiruvalla",
      "Vechoochira",
  ],
  "Kollam": [
      "Anchal",
      "Anchalummoodu",
      "Chadayamangalam",
      "Chathannoor",
      "Chavara",
      "East Kallada",
      "Eravipuram",
      "Ezhukone",
      "Kadakkal",
      "Karunagapally",
      "Kilikolloor",
      "Kollam East",
      "Kollam West",
      "Kottarakkara",
      "Kottiyam",
      "Kundara",
      "Kunnicode",
      "Ochira",
      "Paravoor",
      "Parippally",
      "Pathanapuram",
      "Pooyapally",
      "Punalur",
      "Sakthikulangara",
      "Sasthamcotta",
      "Sooranadu",
      "Thekkumbhagam",
      "Thenmala",
      "Yeroor",
  ],
  "Thiruvananthapuram": [
      "Anchuthengu",
      "Aryanad",
      "Aryancode",
      "Attingal",
      "Balaramapuram",
      "Cantonment PS",
      "Chirayinkeezhu",
      "Fort PS",
      "Kadakkavoor",
      "Kadinamkulam",
      "Kallambalam",
      "Kanjiramkulam",
      "Karamana",
      "Kattakada",
      "Kazhakkuttom",
      "Kilimanoor",
      "Kovalam",
      "Malayinkeezh",
      "Mangalapuram",
      "Maranallor",
      "Medical College",
      "Museum PS",
      "Nedumangad",
      "Nemom",
      "Neyyardam",
      "Neyyattinkara",
      "Pallickal",
      "Palode",
      "Pangode",
      "Parassala",
      "Peroorkada",
      "Pettah",
      "Ponmudi",
      "Poojappura",
      "Poonthura",
      "Poovar",
      "Pothencode",
      "Pozhiyoor",
      "Sreekariyam",
      "Thampanoor",
      "Thiruvallam",
      "Thumba",
      "Valiyamala",
      "Valiyathura",
      "Vanchiyoor",
      "Vanitha PS WSI-1",
      "Varkala",
      "Vattappara",
      "Vattiyoorkavu",
      "Vellarada",
      "Venjaramoodu",
      "Vilappilssala",
      "Vithura",
      "Vizhinjam",
  ]
}